import type { Gang, Pin, Territory } from "@/lib/types";

const now = "2026-01-01T00:00:00.000Z";

export const SEED_GANGS: Gang[] = [
  {
    id: "gang-gsf",
    name: "Grove Street Families",
    tag: "GSF",
    color: "#2ecc71",
    status: "active",
    leader: "",
    description: "South LS classic. Davis and Grove.",
    members: "",
    notes: "",
    logo: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gang-ballas",
    name: "Ballas",
    tag: "BLS",
    color: "#9b59b6",
    status: "active",
    leader: "",
    description: "Davis / Chamberlain.",
    members: "",
    notes: "",
    logo: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gang-vagos",
    name: "Los Santos Vagos",
    tag: "VGS",
    color: "#f1c40f",
    status: "active",
    leader: "",
    description: "East side — Rancho to El Burro.",
    members: "",
    notes: "",
    logo: "",
    createdAt: now,
    updatedAt: now,
  },
];

/** Turf in GTA V game XY (lat = Y, lng = X). */
export const SEED_TERRITORIES: Territory[] = [
  {
    id: "turf-gsf-davis",
    gangId: "gang-gsf",
    name: "Davis / Grove",
    kind: "turf",
    color: null,
    polygon: [
      { lat: -1680, lng: 40 },
      { lat: -1680, lng: 230 },
      { lat: -1860, lng: 230 },
      { lat: -1860, lng: 40 },
    ],
    notes: "Grove Street and the Davis blocks.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "turf-ballas-chamberlain",
    gangId: "gang-ballas",
    name: "Chamberlain Hills",
    kind: "turf",
    color: null,
    polygon: [
      { lat: -1500, lng: -280 },
      { lat: -1500, lng: -40 },
      { lat: -1680, lng: -40 },
      { lat: -1680, lng: -280 },
    ],
    notes: "Chamberlain and the Forum Drive cut.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "turf-vagos-rancho",
    gangId: "gang-vagos",
    name: "Rancho / El Burro",
    kind: "claimed",
    color: null,
    polygon: [
      { lat: -1740, lng: 280 },
      { lat: -1740, lng: 560 },
      { lat: -1980, lng: 560 },
      { lat: -1980, lng: 280 },
    ],
    notes: "East LS yellow.",
    createdAt: now,
    updatedAt: now,
  },
];

export const SEED_PINS: Pin[] = [
  {
    id: "pin-gsf-grove",
    gangId: "gang-gsf",
    name: "Grove Street throw-up",
    kind: "throw-up",
    color: null,
    lat: -1750,
    lng: 112,
    notes: "Green GSF on the wall by the house.",
    dateFound: "2026-01-01",
    image: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pin-ballas-forum",
    gangId: "gang-ballas",
    name: "Forum Drive mural",
    kind: "mural",
    color: null,
    lat: -1595,
    lng: -165,
    notes: "",
    dateFound: "2026-01-01",
    image: "",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pin-vagos-elburro",
    gangId: "gang-vagos",
    name: "El Burro stencil",
    kind: "stencil",
    color: null,
    lat: -1923,
    lng: 1491,
    notes: "",
    dateFound: "2026-01-01",
    image: "",
    createdAt: now,
    updatedAt: now,
  },
];
